/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#eae8e3',
        tertiary: '#006c52',
        'primary-fixed': '#e4dfff',
        'on-surface-variant': '#47464f',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e4e2dd',
        secondary: '#5f5e5c',
        'on-secondary': '#ffffff',
        'outline-variant': '#c8c5d1',
        'on-background': '#1b1c19',
        'surface-dim': '#dcdad5',
        'secondary-fixed-dim': '#c8c6c3',
        'on-error-container': '#93000a',
        'surface-container-low': '#f5f3ee',
        error: '#ba1a1a',
        'inverse-surface': '#30312e',
        'tertiary-fixed-dim': '#6edab4',
        'on-primary-container': '#413c77',
        'inverse-on-surface': '#f2f1ec',
        'surface-container': '#f0eee9',
        'surface-tint': '#5c5794',
        'on-error': '#ffffff',
        surface: '#fbf9f4',
        'on-secondary-container': '#636260',
        'on-secondary-fixed-variant': '#474744',
        primary: '#5c5794',
        'surface-bright': '#fbf9f4',
        'error-container': '#ffdad6',
        background: '#fbf9f4',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#443f7a',
        'inverse-primary': '#c6c0ff',
        'on-surface': '#1b1c19',
        'on-tertiary-container': '#004d3a',
        'on-primary-fixed': '#18114c',
        'on-secondary-fixed': '#1b1c1a',
        'secondary-container': '#e2dfdc',
        'on-tertiary-fixed': '#002117',
        'on-tertiary-fixed-variant': '#00513d',
        'tertiary-fixed': '#8af7cf',
        'tertiary-container': '#56c39e',
        'primary-fixed-dim': '#c6c0ff',
        'secondary-fixed': '#e5e2df',
        outline: '#787680',
        'primary-container': '#afa9ec',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e4e2dd',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['DM Sans', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
